package in.sminfo.tool.mgmt.enums;

public enum EventAction {

	TEAM_CREATION("TEAM_CREATION"),

	TEAM_DELETION("TEAM_DELETION"), 
	
	TEAM_USER_ADDED("TEAM_USER_ADDED"),
	
	TEAM_USER_DELETED("TEAM_USER_DELETED"),

	USER_CREATION("USER_CREATION"),

	USER_DELETION("USER_DELETION"),

	AWS_ACCOUNT_CREATION("AWS_ACCOUNT_CREATION"),

	AWS_ACCOUNT_DELETION("AWS_ACCOUNT_DELETION"),

	SSH_USER_CREATION("SSH_USER_CREATION"),

	SSH_USER_DELETION("SSH_USER_DELETION"),

	SSH_ACCESS("SSH_ACCESS"),
	
	VPC_WHITELISTED("VPC_WHITELISTED"),
	
	VPC_REMOVED_WHITELISTED("VPC_REMOVED_WHITELISTED"),
	
	GERRIT_USER_ACTIVATED("GERRIT_USER_ACTIVATED"),
	
	GERRIT_USER_DEACTIVATED("GERRIT_USER_DEACTIVATED"),
	
	USER_PRIVILEGE_UPDATED("USER_PRIVILEGE_UPDATED");
	
	
	

	private String _type;

	EventAction(String type) {
		this._type = type;
	}

	@Override
	public String toString() {
		return this._type;
	}

}
